# Generated by Django 5.2.6 on 2025-09-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nazwa")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "tg_channel_id",
                    models.CharField(max_length=128, verbose_name="ID kanału Telegram"),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Token bota",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="pl", max_length=8, verbose_name="Język"),
                ),
                (
                    "max_chars",
                    models.IntegerField(
                        default=1000, verbose_name="Maks. liczba znaków"
                    ),
                ),
                (
                    "emoji_min",
                    models.IntegerField(default=1, verbose_name="Min. liczba emoji"),
                ),
                (
                    "emoji_max",
                    models.IntegerField(default=6, verbose_name="Maks. liczba emoji"),
                ),
                (
                    "footer_text",
                    models.TextField(
                        default="🇵🇱 t.me/sztuka_wojny\n💬 @sztukawojny",
                        verbose_name="Stopka (2 linie)",
                    ),
                ),
                (
                    "no_links_in_text",
                    models.BooleanField(
                        default=True, verbose_name="Bez linków w treści"
                    ),
                ),
                (
                    "auto_blur_default",
                    models.BooleanField(
                        default=True, verbose_name="Domyślny blur (spoiler)"
                    ),
                ),
                (
                    "draft_target_count",
                    models.IntegerField(
                        default=20, verbose_name="Docelowa liczba draftów"
                    ),
                ),
                (
                    "draft_ttl_days",
                    models.IntegerField(
                        default=3, verbose_name="Czas życia draftu (dni)"
                    ),
                ),
                (
                    "slot_step_min",
                    models.IntegerField(
                        default=30, verbose_name="Krok slotów (minuty)"
                    ),
                ),
                (
                    "slot_start_hour",
                    models.IntegerField(default=6, verbose_name="Godzina startu"),
                ),
                (
                    "slot_end_hour",
                    models.IntegerField(default=23, verbose_name="Godzina końca"),
                ),
                (
                    "slot_end_minute",
                    models.IntegerField(default=30, verbose_name="Minuta końca"),
                ),
                (
                    "style_prompt",
                    models.TextField(
                        default="Jesteś redaktorem polskojęzycznego kanału informacyjnego. Piszesz TYLKO po polsku (UTF-8). Styl: krótko, wojskowo, rzeczowo; 1–3 akapity z liczbami i faktami; ≤1000 znaków; 1–3 emoji; bez linków/hashtagów w treści; na końcu stopka w 2 liniach.",
                        verbose_name="Prompt stylu (PL)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kanał",
                "verbose_name_plural": "Kanały",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Treść")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("APPROVED", "APPROVED"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zaplanowano na"
                    ),
                ),
                (
                    "schedule_mode",
                    models.CharField(
                        choices=[("AUTO", "AUTO"), ("MANUAL", "MANUAL")],
                        default="AUTO",
                        max_length=6,
                        verbose_name="Tryb planowania",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "dupe_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Podobieństwo (duplikat)"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        default="gpt", max_length=8, verbose_name="Pochodzenie"
                    ),
                ),
                (
                    "generated_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="Prompt generujący"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Wygasa"),
                ),
                (
                    "message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID wiadomości (tekst)"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zatwierdził",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="posts.channel",
                        verbose_name="Kanał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wpis",
                "verbose_name_plural": "Wpisy",
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "photo"),
                            ("video", "video"),
                            ("doc", "doc"),
                        ],
                        max_length=8,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True, default="", verbose_name="Źródłowy URL"
                    ),
                ),
                (
                    "cache_path",
                    models.TextField(
                        blank=True, default="", verbose_name="Ścieżka cache"
                    ),
                ),
                (
                    "tg_file_id",
                    models.TextField(
                        blank=True, default="", verbose_name="Telegram file_id"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "has_spoiler",
                    models.BooleanField(default=False, verbose_name="Ukryj (spoiler)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Wygasa"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="posts.post",
                        verbose_name="Wpis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medium wpisu",
                "verbose_name_plural": "Media wpisu",
                "ordering": ["order", "id"],
            },
        ),
    ]
