# Generated by Django 5.2.6 on 2025-09-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_channel_id_alter_post_id_alter_postmedia_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftPost",
            fields=[],
            options={
                "verbose_name": "Draft",
                "verbose_name_plural": "Drafty",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("posts.post",),
        ),
        migrations.CreateModel(
            name="ScheduledPost",
            fields=[],
            options={
                "verbose_name": "Pozycja harmonogramu",
                "verbose_name_plural": "Harmonogram",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("posts.post",),
        ),
    ]
