# Generated by Django 5.2.7 on 2025-10-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_source_metadata_postmedia_resolver"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Nazwa")),
                ("url", models.URLField(max_length=500, verbose_name="Adres URL")),
                (
                    "priority",
                    models.PositiveIntegerField(default=1, verbose_name="Priorytet"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywne"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Zmieniono"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="posts.channel",
                        verbose_name="Kanał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Źródło kanału",
                "verbose_name_plural": "Źródła kanału",
                "ordering": ("-is_active", "-priority", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "url"),
                        name="posts_channelsource_unique_channel_url",
                    )
                ],
            },
        ),
    ]
