# Generated by Django 5.2.7 on 2025-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_channelsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="source_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Źródło treści"
            ),
        ),
    ]
