# Generated by Django 5.2.7 on 2025-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_post_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryPost",
            fields=[],
            options={
                "verbose_name": "Historia wpisu",
                "verbose_name_plural": "Historia",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("posts.post",),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Opublikowano"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("APPROVED", "APPROVED"),
                    ("SCHEDULED", "SCHEDULED"),
                    ("PUBLISHING", "PUBLISHING"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="DRAFT",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
