# Generated by Django 5.2.7 on 2025-10-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_historypost_post_published_at_alter_post_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="emoji_max",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="emoji_min",
        ),
    ]
